### ISSUE TITLE
Waiting for '/controller_manager' node to exist

### ISSUE THREAD

**Issue by KaushalkumarPatel** [agilexrobotics/ugv_gazebo_sim#30]
Hi, 

I have clone humble branch to use Gazebo SIm for ranger. I did the steps according to the README.md file. 

But in the Step 3. when I launch this command `ros2 launch ranger_mini ranger_mini_v2_gazebo.launch.py ` then Gazebo took lot of time to load and in the terminal the errors are as follows.

`[spawner-6] [INFO] [1719220227.763127103] [spawner_forward_position_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [INFO] [1719220227.828710753] [spawner_forward_velocity_controller]: Waiting for '/controller_manager' node to exist
[spawner-8] [INFO] [1719220227.963003767] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-6] [INFO] [1719220229.785935611] [spawner_forward_position_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [INFO] [1719220229.849734137] [spawner_forward_velocity_controller]: Waiting for '/controller_manager' node to exist
[spawner-8] [INFO] [1719220229.985608295] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-6] [INFO] [1719220231.809951986] [spawner_forward_position_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [INFO] [1719220231.872643639] [spawner_forward_velocity_controller]: Waiting for '/controller_manager' node to exist
[spawner-8] [INFO] [1719220232.011935022] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-6] [INFO] [1719220233.839252074] [spawner_forward_position_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [INFO] [1719220233.898432816] [spawner_forward_velocity_controller]: Waiting for '/controller_manager' node to exist
[spawner-8] [INFO] [1719220234.037101024] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-6] [ERROR] [1719220235.860525422] [spawner_forward_position_controller]: Controller manager not available
[spawner-7] [ERROR] [1719220235.920445497] [spawner_forward_velocity_controller]: Controller manager not available
[ERROR] [spawner-6]: process has died [pid 37189, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner forward_position_controller --ros-args'].
[spawner-8] [ERROR] [1719220236.057679162] [spawner_joint_state_broadcaster]: Controller manager not available
[ERROR] [spawner-7]: process has died [pid 37191, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner forward_velocity_controller --ros-args'].
[ERROR] [spawner-8]: process has died [pid 37193, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner joint_state_broadcaster --ros-args'].
[spawn_entity.py-3] [ERROR] [1719220256.216862855] [spawn_entity]: Service %s/spawn_entity unavailable. Was Gazebo started with GazeboRosFactory?
[spawn_entity.py-3] [ERROR] [1719220256.218582094] [spawn_entity]: Spawn service failed. Exiting.
[ERROR] [spawn_entity.py-3]: process has died [pid 37183, exit code 1, cmd '/opt/ros/humble/lib/gazebo_ros/spawn_entity.py -entity ranger_mini_v2 -topic robot_description -x 0.0 -y 0.0 -z 0.0 -Y 0.00 --ros-args'].
c^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[robot_state_publisher-4] [INFO] [1719221039.233395906] [rclcpp]: signal_handler(signum=2)
[robot_control.py-5] Traceback (most recent call last):
[robot_control.py-5]   File "/home/administrator/ranger_ws/install/four_ws_control/lib/four_ws_control/robot_control.py", line 166, in <module>
[robot_control.py-5]     rclpy.shutdown()
[robot_control.py-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 126, in shutdown
[robot_control.py-5]     _shutdown(context=context)
[robot_control.py-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/utilities.py", line 58, in shutdown
[robot_control.py-5]     return context.shutdown()
[robot_control.py-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/context.py", line 102, in shutdown
[robot_control.py-5]     self.__context.shutdown()
[robot_control.py-5] rclpy._rclpy_pybind11.RCLError: failed to shutdown: rcl_shutdown already called on the given context, at ./src/rcl/init.c:241
[INFO] [robot_state_publisher-4]: process has finished cleanly [pid 37185]
[INFO] [gzclient-2]: process has finished cleanly [pid 37181]
[INFO] [gzserver-1]: process has finished cleanly [pid 37179]
[ERROR] [robot_control.py-5]: process has died [pid 37187, exit code 1, cmd '/home/administrator/ranger_ws/install/four_ws_control/lib/four_ws_control/robot_control.py --ros-args'].`

There is nothing inside the Gazebo environment.

**Comment by KaushalkumarPatel** [comment]
Inside ranger_mini/CMakeLists.txt, I did the following editing. 

```
install(
  DIRECTORY launch config meshes rviz urdf 
  DESTINATION share/${PROJECT_NAME}
)
```

**Comment by Grange007** [comment]
Has anyone else met the problem? I'm troubled with the same problem that '/controller_manager' node doesn't exist, but I can't solve it as KaushalkumarPatel said
